# 简化的配置文件
app:
    name: "示例应用"
    version: "1.0.0"
    environment: "development"

server:
    host: "localhost"
    port: 8080
    debug: true

database:
    primary:
        host: "localhost"
        port: 5432
        name: "myapp"
        url: "postgres://user:pass@localhost:5432/myapp"
    replicas:
        - "postgres://user:pass@slave1:5432/myapp"

features:
    - "auth"
    - "logging"
    - "metrics"
