# 简化的配置文件 - 使用新的字段名称
application:
    app_name: "示例应用"
    version: "1.0.0"
    env: "development"

server:
    bind_address: "localhost"
    port: 8080
    debug_mode: true

database:
    primary:
        host: "localhost"
        port: 5432
        database_name: "myapp"
        connection_url: "postgres://user:pass@localhost:5432/myapp"
    read_replicas:
        - "postgres://user:pass@slave1:5432/myapp"

feature_flags:
    - "auth"
    - "logging"
    - "metrics"
